apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "ran.openshift.io/v1alpha1",
          "kind": "ImageBasedUpgrade",
          "metadata": {
            "name": "ImageBasedUpgrade-sample"
          },
          "spec": null
        }
      ]
    capabilities: Basic Install
    createdAt: "2023-09-07T18:13:41Z"
    operators.operatorframework.io/builder: operator-sdk-v1.28.0-ocp
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: lifecycle-agent.v4.14.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: ImageBasedUpgrade is the Schema for the ImageBasedUpgrades API
      displayName: Image-based Cluster Upgrade
      kind: ImageBasedUpgrade
      name: imagebasedupgrades.ran.openshift.io
      resources:
      - kind: Deployment
        name: ""
        version: apps/v1
      - kind: Namespace
        name: ""
        version: v1
      statusDescriptors:
      - displayName: Status
        path: observedGeneration
      version: v1alpha1
  description: blah
  displayName: Openshift Lifecycle Agent
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - prometheusrules
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ran.openshift.io
          resources:
          - imagebasedupgrades
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ran.openshift.io
          resources:
          - imagebasedupgrades/finalizers
          verbs:
          - update
        - apiGroups:
          - ran.openshift.io
          resources:
          - imagebasedupgrades/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: lifecycle-agent-controller-manager
      deployments:
      - label:
          app.kubernetes.io/component: lifecycle-agent
          app.kubernetes.io/name: lifecyle-agent-operator
          control-plane: controller-manager
        name: lifecycle-agent-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              app.kubernetes.io/component: lifecycle-agent
              app.kubernetes.io/name: lifecyle-agent-operator
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              labels:
                app.kubernetes.io/component: lifecycle-agent
                app.kubernetes.io/name: lifecyle-agent-operator
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                command:
                - /manager
                image: quay.io/junchen/lifecycle-agent:4.14.0
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  requests:
                    cpu: 100m
                    memory: 20Mi
                securityContext:
                  allowPrivilegeEscalation: false
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=10
                image: quay.io/openshift/origin-kube-rbac-proxy:4.12
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                resources: {}
              securityContext:
                runAsNonRoot: true
              serviceAccountName: lifecycle-agent-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: lifecycle-agent-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - upgrade
  links:
  - name: Lifecycle Agent
    url: https://lifecycle-agent.domain
  maturity: alpha
  provider:
    name: Red Hat
  version: 4.14.0
