apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: lifecycle-agent-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - delete
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - config.openshift.io
  resources:
  - clusterversions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - config.openshift.io
  resources:
  - imagedigestmirrorsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - lca.openshift.io
  resources:
  - imagebasedupgrades
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lca.openshift.io
  resources:
  - imagebasedupgrades/finalizers
  verbs:
  - update
- apiGroups:
  - lca.openshift.io
  resources:
  - imagebasedupgrades/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - monitoring.coreos.com
  resources:
  - prometheusrules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operators.coreos.com/v1alpha1
  resources:
  - clusterserviceversions
  verbs:
  - delete
  - get
  - list
- apiGroups:
  - operators.coreos.com/v1alpha1
  resources:
  - subscriptions
  verbs:
  - delete
  - get
  - list
- apiGroups:
  - velero.io/v1
  resources:
  - backups
  verbs:
  - create
  - delete
  - get
  - list
  - update
- apiGroups:
  - velero.io/v1
  resources:
  - backupstoragelocations
  verbs:
  - get
  - list
- apiGroups:
  - velero.io/v1
  resources:
  - restores
  verbs:
  - create
  - delete
  - get
  - list
  - update
