apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: lifecycle-agent
    app.kubernetes.io/name: lifecycle-agent-operator
    control-plane: controller-manager
  name: lifecycle-agent-controller-manager-metrics-service
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    app.kubernetes.io/component: lifecycle-agent
    app.kubernetes.io/name: lifecycle-agent-operator
    control-plane: controller-manager
status:
  loadBalancer: {}
