apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: lifecycle-agent.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: ImageBasedUpgrade is the Schema for the ImageBasedUpgrades API
      displayName: Image-based Cluster Upgrade
      kind: ImageBasedUpgrade
      name: imagebasedupgrades.ran.openshift.io
      resources:
      - kind: Deployment
        name: ""
        version: apps/v1
      - kind: Namespace
        name: ""
        version: v1
      statusDescriptors:
      - displayName: Status
        path: observedGeneration
      version: v1alpha1
  description: blah
  displayName: Openshift Lifecycle Agent
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - upgrade
  links:
  - name: Lifecycle Agent
    url: https://lifecycle-agent.domain
  maturity: alpha
  provider:
    name: Red Hat
  version: 0.0.1
