apiVersion: lca.openshift.io/v1alpha1
kind: ImageBasedUpgrade
metadata:
  name: upgrade
spec:
  stage: Idle
  seedImageRef:
    version: 4.15.0
    image: quay.io/xyz
  additionalImages:
    name: ""
    namespace: ""
  autoRollbackOnFailure: {}
  extraManifests:
  - name: sno-extramanifests
    namespace: openshift-lifecycle-agent
  oadpContent:
    - name: oadp-cm-sno-backup
      namespace: openshift-adp


